name: vi_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  syncfusion_flutter_pdfviewer: ^31.2.4
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  js: ^0.7.2
  flutter_dotenv: ^6.0.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
   - .env
   - assets/doc/
   - assets/